ignore = [
    # spring13/homework1
    { id = "OBS-STAN-0005-YrzpQi-51:35" },
    { id = "OBS-STAN-0006-u5IQ8D-11:26" },
    { id = "OBS-STAN-0101-u5IQ8D-17:21" },
    { id = "OBS-STAN-0101-u5IQ8D-17:53" },
    { id = "OBS-STAN-0101-vU5tw7-4:12" },
    { id = "OBS-STAN-0103-YrzpQi-19:12" },
    { id = "OBS-STAN-0103-YrzpQi-26:19" },
    { id = "OBS-STAN-0103-YrzpQi-26:57" },
    { id = "OBS-STAN-0103-YrzpQi-50:3" },
    { id = "OBS-STAN-0103-YrzpQi-77:9" },
    { id = "OBS-STAN-0103-u5IQ8D-31:12" },
    { id = "OBS-STAN-0105-JdazAf-6:13" },
    { id = "OBS-STAN-0105-JdazAf-6:24" },

    # spring13/homework2
    { id = "OBS-STAN-0009-vU5tw7-12:48" },
    { id = "OBS-STAN-0009-vU5tw7-14:25" },
    { id = "OBS-STAN-0009-vU5tw7-16:24" },
    { id = "OBS-STAN-0009-vU5tw7-16:41" },
    { id = "OBS-STAN-0206-i/leo3-22:10" },
    { id = "OBS-STAN-0206-i/leo3-22:39" },

    # spring13/homework3
    { id = "OBS-STAN-0013-JdazAf-16:13" },
    { id = "OBS-STAN-0013-YrzpQi-38:15" },
    { id = "OBS-STAN-0103-JdazAf-21:35" },
    { id = "OBS-STAN-0103-YrzpQi-24:16" },
    { id = "OBS-STAN-0103-YrzpQi-24:40" },
    { id = "OBS-STAN-0103-YrzpQi-27:16" },
    { id = "OBS-STAN-0103-YrzpQi-27:46" },
    { id = "OBS-STAN-0103-YrzpQi-38:29" },

    # spring13/homework4
    { id = "OBS-STAN-0013-u5IQ8D-18:22" },
    { id = "OBS-STAN-0013-u5IQ8D-22:22" },
    { id = "OBS-STAN-0101-JdazAf-14:43" },
    { id = "OBS-STAN-0101-YrzpQi-85:47" },
    { id = "OBS-STAN-0103-YrzpQi-125:10" },
    { id = "OBS-STAN-0103-YrzpQi-74:34" },
    { id = "OBS-STAN-0105-vU5tw7-8:8" },
    { id = "OBS-STAN-0106-vU5tw7-5:8" },
    { id = "OBS-STAN-0206-mfX/Y3-7:18" },
    { id = "OBS-STAN-0206-mfX/Y3-7:30" },

    # spring13/homework5
    { id = "OBS-STAN-0206-gBa+qh-5:9" },
    { id = "OBS-STAN-0206-gBa+qh-5:15" },
    { id = "OBS-STAN-0206-gBa+qh-6:9" },
    { id = "OBS-STAN-0206-gBa+qh-6:15" },
    { id = "OBS-STAN-0206-Gzz1Az-21:9" },
    { id = "OBS-STAN-0206-Gzz1Az-21:14" },
    { id = "OBS-STAN-0206-Gzz1Az-22:9" },
    { id = "OBS-STAN-0206-Gzz1Az-22:14" },
]
