ignore = [
    { id = "OBS-STAN-0005-YrzpQi-53:76" },
    { id = "OBS-STAN-0006-u5IQ8D-12:26" },
    { id = "OBS-STAN-0101-u5IQ8D-22:21" },
    { id = "OBS-STAN-0101-u5IQ8D-22:53" },
    { id = "OBS-STAN-0101-vU5tw7-4:12" },
    { id = "OBS-STAN-0103-YrzpQi-21:12" },
    { id = "OBS-STAN-0103-YrzpQi-26:19" },
    { id = "OBS-STAN-0103-YrzpQi-26:57" },
    { id = "OBS-STAN-0103-YrzpQi-53:12" },
    { id = "OBS-STAN-0103-YrzpQi-73:46" },
    { id = "OBS-STAN-0103-u5IQ8D-31:12" },
    { id = "OBS-STAN-0105-JdazAf-6:13" },
    { id = "OBS-STAN-0105-JdazAf-6:24" },
]
